PROJECT = ridhm_pubsub
PROJECT_DESCRIPTION = Ridhm Pubsub
PROJECT_VERSION = 1

DEPS = bullet amqp_client cowboy eredis_smart_sub jsx getopt uuid
dep_getopt = git https://github.com/jcomellas/getopt master
dep_bullet = git https://github.com/extend/bullet.git master
dep_amqp_client = git git://github.com/jbrisbin/amqp_client.git rabbitmq-3.6.2
dep_eredis_smart_sub = git git://github.com/nacmartin/eredis_smart_sub.git master
dep_jsx = git git://github.com/talentdeficit/jsx.git master
dep_uuid = git git://github.com/avtobiff/erlang-uuid.git master
dep_cowboy_commit = master
include ./erlang.mk
